<script setup>
import { computed, onMounted, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { authStore, clearSession } from '../lib/auth'
import { CONTACT } from '../lib/contact'
import { api } from '../lib/api'
import TrackOrderPage from './TrackOrderPage.vue'
import ReturnsPage from './ReturnsPage.vue'
import CartPage from './CartPage.vue'
import { cartStore, refreshCart } from '../lib/cart'

const route=useRoute(), router=useRouter(), toast=ref(''), search=ref(''), status=ref('All'), selected=ref(null)
const accountMenuItems = [
  ['overview', 'Overview'],
  ['orders', 'My Orders'],
  ['track', 'Track Order'],
  ['returns', 'Returns & Exchanges'],
  ['bag', 'My Cart'],
  ['wishlist', 'Wishlist'],
  ['looks', 'Saved Looks'],
  ['recent', 'Recently Viewed'],
  ['style', 'My Sizes & Style'],
  ['loyalty', 'Loyalty & Rewards'],
  ['coupons', 'Coupons'],
  ['credit', 'Gift Cards & Credit'],
  ['addresses', 'Addresses'],
  ['notifications', 'Notifications'],
  ['reviews', 'Reviews & Questions'],
  ['referrals', 'Referrals'],
  ['support', 'Support Centre'],
  ['profile', 'Profile'],
  ['security', 'Privacy & Security'],
]
const tabs = accountMenuItems.map(([tab]) => tab)
const activeTab=computed(()=>tabs.includes(route.query.tab)?route.query.tab:'overview')
// Below 600px the sidebar becomes a fixed drawer (see .dashboard-layout.nav-open
// in styles.css) instead of the horizontal-scroll tab strip used at wider mobile
// widths — with 19 sections, that strip only shows ~1 at a time with no visual
// hint it scrolls, which reads as "the menu is missing".
const mobileNavOpen=ref(false)
const profile=reactive({name:'',email:authStore.user?.email||'',phone:'',whatsapp:'',birthday:'',language:'English',currency:'USD'})
const name=computed(()=>profile.name||authStore.user?.email?.split('@')[0].replace(/[._-]/g,' ')||'there')
const initials=computed(()=>name.value.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase())
const orders=ref([])
const filteredOrders=computed(()=>orders.value.filter(o=>(status.value==='All'||o.status===status.value)&&o.number.toLowerCase().includes(search.value.toLowerCase())))
const wishlist=ref([])
const looks=ref([])
const recent=ref([])
const notices=ref([])
const addresses=ref([])
const address=reactive({label:'Home',recipient:'',phone:'',province:'',city:'',suburb:'',street:'',house:'',instructions:''})
const profilePhoto=ref(''), review=reactive({product:'',rating:0,comment:'',fit:''}), question=reactive({product:'',message:''})
const backendReady=ref(false), deliveryQuote=ref(null)
const profileSaveState=ref('saved')
let profileSaveTimer
const styleProfile=reactive({clothingSize:'',shoeSize:'',fit:'',colours:'',styles:'',priceRange:'',brands:'',occasions:'',fragrance:''})
const prefs=reactive({Email:true,SMS:false,WhatsApp:true,'Browser push':true,'Order updates':true,Promotions:false,'Stock alerts':true,'Price drops':true,'Loyalty updates':true,Newsletter:false})
const privacy=reactive({twoFactor:false,marketing:false,cookies:true})
const ticket=reactive({category:'Order problem',order:'',subject:'',message:''})
onMounted(async()=>{localStorage.removeItem('mk_dashboard');window.addEventListener('mk-sync',handleLiveSync);await Promise.all([syncDashboard(),refreshCart()])})
onBeforeUnmount(()=>window.removeEventListener('mk-sync',handleLiveSync))
function handleLiveSync(event){if(event.detail?.type==='customer'||event.detail?.type==='platform')syncDashboard()}
watch(wishlist,(next,previous)=>{if(!backendReady.value)return;const ids=new Set(next.map(x=>x.id));previous.filter(x=>x.id&&!ids.has(x.id)).forEach(x=>api.deleteDashboardRecord('wishlists',x.id).catch(()=>{}))},{deep:false})
watch(looks,(next,previous)=>{if(!backendReady.value)return;const ids=new Set(next.map(x=>x.id));previous.filter(x=>x.id&&!ids.has(x.id)).forEach(x=>api.deleteDashboardRecord('saved-outfits',x.id).catch(()=>{}))},{deep:false})
watch(recent,(next,previous)=>{if(!backendReady.value)return;const ids=new Set(next.map(x=>x.id));previous.filter(x=>x.id&&!ids.has(x.id)).forEach(x=>api.deleteDashboardRecord('search-history',x.id).catch(()=>{}))},{deep:false})
watch(privacy,()=>{if(backendReady.value)savePrivacy().catch(e=>flash(e.message))},{deep:true})
watch([profile,profilePhoto],()=>{if(!backendReady.value)return;profileSaveState.value='saving';clearTimeout(profileSaveTimer);profileSaveTimer=setTimeout(()=>saveProfile(true),600)},{deep:true})
function go(tab){router.replace({name:'account',query:tab==='overview'?{}:{tab}});mobileNavOpen.value=false}
function flash(x){toast.value=x;setTimeout(()=>toast.value='',2200)}
async function addAddress(){const quote=await api.getDeliveryQuote(address.city);const data={label:address.label,recipient:address.recipient,phone:address.phone,address:[address.house,address.street,address.suburb,address.city,address.province].filter(Boolean).join(', '),city:address.city,instructions:address.instructions,default:!addresses.value.length,deliveryFee:quote.fee};const saved=await api.createDashboardRecord('addresses',data);addresses.value.push({id:saved.id,...saved.data});Object.keys(address).forEach(k=>address[k]='');address.label='Home';deliveryQuote.value=null;flash(quote.message+' — address saved')}
function logout(){clearSession();router.replace({name:'home'})}
async function syncDashboard(){try{profile.name='';profile.email=authStore.user?.email||'';profile.phone='';profile.whatsapp='';profile.birthday='';profile.language='English';profile.currency='USD';profilePhoto.value='';orders.value=[];wishlist.value=[];looks.value=[];recent.value=[];notices.value=[];addresses.value=[];const s=await api.getCustomerDashboard();const r=s.resources||{};if(s.customer){profile.name=s.customer.name||'';profile.phone=s.customer.phone||''}if(s.profile?.data){Object.assign(profile,s.profile.data);profile.email=authStore.user?.email||profile.email;profilePhoto.value=s.profile.data.photo||''}orders.value=(s.orders||[]).map(o=>({number:o.orderNumber,date:new Date(o.createdAt).toLocaleDateString(),status:o.status,total:o.total,items:o.items||[]}));if(r.addresses?.length)addresses.value=r.addresses.map(x=>({id:x.id,...x.data}));if(r.notifications?.length)notices.value=r.notifications.map(x=>({id:x.id,...x.data}));if(r.wishlists?.length)wishlist.value=r.wishlists.map(x=>({id:x.id,...x.data}));if(r['saved-outfits']?.length)looks.value=r['saved-outfits'].map(x=>({id:x.id,...x.data}));if(r['search-history']?.length)recent.value=r['search-history'].map(x=>({id:x.id,...x.data,date:x.data.viewedAt?new Date(x.data.viewedAt).toLocaleDateString():''}));if(r['styling-profiles']?.[0]?.data)Object.assign(styleProfile,r['styling-profiles'][0].data);if(r['consent-records']?.[0]?.data)Object.assign(privacy,r['consent-records'][0].data);const np=r['notification-preferences']?.[0]?.data;if(np)Object.assign(prefs,np.preferences||{});backendReady.value=true}catch(e){flash(e.message)}}
async function saveProfile(quiet=false){try{profileSaveState.value='saving';await api.saveCustomerProfile({...profile,email:authStore.user?.email||profile.email,photo:profilePhoto.value});profileSaveState.value='saved';if(!quiet)flash('Profile saved permanently')}catch(e){profileSaveState.value='error';flash(e.message)}}
function uploadPhoto(event){const file=event.target.files?.[0];if(!file)return;if(file.size>2_000_000){flash('Photo must be smaller than 2MB');return}const reader=new FileReader();reader.onload=()=>profilePhoto.value=reader.result;reader.readAsDataURL(file)}
async function savePreferences(){await api.createDashboardRecord('notification-preferences',{preferences:{...prefs},channels:Object.keys(prefs).filter(k=>prefs[k])});flash('Notification preferences synced')}
async function submitSupport(){await api.createDashboardRecord('support-tickets',{...ticket,status:'Open',channel:'Dashboard',createdAt:new Date().toISOString()});ticket.subject='';ticket.message='';ticket.order='';await syncDashboard();flash('Support ticket submitted')}
async function submitReview(){if(!review.rating||!review.comment)return flash('Choose a rating and write a review');await api.createDashboardRecord('reviews',{...review,status:'Pending',verifiedPurchase:true});review.comment='';flash('Review sent and visible to staff')}
async function submitQuestion(){if(!question.message)return;await api.createDashboardRecord('product-questions',{...question,status:'Awaiting answer'});question.message='';flash('Question sent to the product team')}
async function shareReferral(){if(!profile.phone)return flash('Add and save your phone number in Profile first');const code=profile.phone.replace(/\D/g,'');const link=`${location.origin}/register?ref=${encodeURIComponent(code)}`;await api.createDashboardRecord('affiliate-codes',{code,link,phone:profile.phone,status:'Active'});window.open(`https://wa.me/?text=${encodeURIComponent('Shop Maps Kayz with my referral link: '+link)}`,'_blank');}
async function checkDelivery(){deliveryQuote.value=await api.getDeliveryQuote(address.city)}
async function removeRecord(resource,item,list){await api.deleteDashboardRecord(resource,item.id);list.value=list.value.filter(x=>x.id!==item.id);flash('Removed')}
async function markNotice(n){if(n.read)return;n.read=true;await api.updateDashboardRecord('notifications',n.id,{read:true})}
async function saveStyle(){await api.createDashboardRecord('styling-profiles',{...styleProfile});flash('Style profile saved to database')}
async function savePrivacy(){await api.createDashboardRecord('consent-records',{...privacy,updatedAt:new Date().toISOString()});flash('Privacy settings saved to database')}
async function clearHistory(){await Promise.all(recent.value.filter(x=>x.id).map(x=>api.deleteDashboardRecord('search-history',x.id)));recent.value=[];flash('Viewing history cleared')}
</script>

<template><div class="customer-dashboard"><div v-if="toast" class="dashboard-toast">{{toast}}</div>
<header class="dashboard-hero"><div><p class="eyebrow dark">Customer dashboard</p><h1>Welcome back,<br><em>{{name}}.</em></h1><p>Your orders, style, rewards and account — all in one place.</p></div><div class="profile-chip"><img v-if="profilePhoto" :src="profilePhoto" alt="Profile photo"><span v-else>{{initials}}</span><div><strong>{{profile.name||authStore.user?.email}}</strong><small>{{authStore.user?.email}} · Customer account</small></div></div></header>
<div class="dashboard-layout" :class="{'nav-open':mobileNavOpen}"><button type="button" class="dashboard-menu-button" aria-label="Toggle account menu" @click="mobileNavOpen=!mobileNavOpen"><span>{{tabs.indexOf(activeTab)+1}}</span> My account menu ☰</button><div v-if="mobileNavOpen" class="dashboard-nav-backdrop" @click="mobileNavOpen=false"></div><aside class="dashboard-sidebar"><p>My account</p><button v-for="(x,i) in accountMenuItems" :key="x[0]" :class="{active:activeTab===x[0]}" @click="go(x[0])"><span>{{String(i+1).padStart(2,'0')}}</span>{{x[1]}}<b v-if="x[0]==='bag'">{{cartStore.itemCount}}</b><b v-if="x[0]==='wishlist'">{{wishlist.length}}</b><b v-if="x[0]==='notifications'">{{notices.filter(n=>!n.read).length}}</b></button><router-link to="/shop" class="dashboard-sidebar-shop"><span>🛍</span>Continue shopping</router-link><button @click="logout"><span>20</span>Log Out</button></aside>
<main class="dashboard-content">
<template v-if="activeTab==='overview'"><section class="dashboard-summary four"><article><span>Active orders</span><strong>{{orders.length}}</strong><button @click="go('orders')">View orders →</button></article><article><span>Cart items</span><strong>{{cartStore.itemCount}}</strong><button @click="go('bag')">View cart →</button></article><article><span>Wishlist</span><strong>{{wishlist.length}}</strong><button @click="go('wishlist')">View wishlist →</button></article><article><span>Notifications</span><strong>{{notices.filter(n=>!n.read).length}}</strong><button @click="go('notifications')">View notifications →</button></article></section>
<section class="dashboard-grid-main"><article class="dashboard-card"><div class="card-heading"><div><p class="eyebrow dark">Orders</p><h2>No active delivery</h2></div></div><p class="safe-note">New order and delivery updates will appear here.</p><button class="text-action" @click="go('track')">Track an order →</button></article><article class="dashboard-card"><p class="eyebrow dark">Quick actions</p><div class="quick-actions"><router-link to="/shop">Continue shopping</router-link><button @click="go('bag')">View cart</button><button @click="go('track')">Track order</button><button @click="go('support')">Contact support</button></div></article></section>
<section class="dashboard-two-col"><article class="dashboard-card"><div class="card-heading"><div><p class="eyebrow dark">Picked for you</p><h2>Recommendations</h2></div></div><div class="product-mini-grid"><div v-for="p in recent.slice(0,2)" :key="p.name"><div class="product-placeholder">MK</div><strong>{{p.name}}</strong><small>US${{p.price}}</small><button @click="flash('We’ll show fewer items like this')">Not interested</button></div></div></article><article class="dashboard-card"><div class="card-heading"><div><p class="eyebrow dark">The latest</p><h2>Notifications</h2></div><button class="text-action" @click="go('notifications')">View all →</button></div><div v-for="n in notices.slice(0,3)" :key="n.id" class="notice-row"><i :class="{unread:!n.read}"></i><div><strong>{{n.title}}</strong><small>{{n.time}}</small></div></div></article></section></template>

<template v-else-if="activeTab==='orders'"><div class="section-title"><p class="eyebrow dark">Purchase history</p><h2>My orders</h2><p>Search, filter, review and reorder your purchases.</p></div><div class="toolbar"><input v-model="search" placeholder="Search order number"><select v-model="status"><option>All</option><option>Out for Delivery</option><option>Delivered</option><option>Returned</option></select></div><article v-for="o in filteredOrders" :key="o.number" class="dashboard-card order-row"><div><small>{{o.date}}</small><strong>{{o.number}}</strong></div><div><small>Status</small><span class="status-pill">{{o.status}}</span></div><div><small>Total</small><span>US${{o.total}}</span></div><button class="btn btn-ghost" @click="selected=selected===o?null:o">{{selected===o?'Close':'View details'}}</button><div v-if="selected===o" class="order-detail"><div class="product-placeholder">MK</div><div><strong>{{o.product}}</strong><p>{{o.detail}} · Qty 1</p><p>{{o.courier}} · {{o.tracking}}</p></div><div class="detail-actions"><button @click="flash('Invoice download started')">Invoice</button><button @click="flash('Receipt download started')">Receipt</button><button @click="flash('Item added to bag')">Reorder</button><button @click="go('support')">Support</button></div></div></article></template>
<CartPage v-else-if="activeTab==='bag'"/><TrackOrderPage v-else-if="activeTab==='track'"/><ReturnsPage v-else-if="activeTab==='returns'"/>
<template v-else-if="activeTab==='wishlist'"><PageTitle eyebrow="Saved for later" title="Wishlist"/><div class="wishlist-grid"><article v-for="x in wishlist" :key="x.id" class="dashboard-card saved-product"><div class="product-placeholder tall">MK</div><span class="stock-note">{{x.stock}}</span><h3>{{x.name}}</h3><p>US${{x.price}} · {{x.size}}</p><input v-model="x.note" placeholder="Add a note"><div><button class="btn btn-primary" @click="flash('Item moved to bag')">Move to bag</button><button class="btn btn-ghost" @click="wishlist=wishlist.filter(w=>w.id!==x.id)">Remove</button></div></article></div></template>
<template v-else-if="activeTab==='looks'"><PageTitle eyebrow="Complete the look" title="Saved looks"/><article v-for="x in looks" :key="x.id" class="dashboard-card look-row"><div class="look-tiles"><i v-for="n in x.items" :key="n">MK</i></div><div><input v-model="x.name" class="inline-name"><p>{{x.items}} pieces · US${{x.price}} · {{x.available?'All available':'1 unavailable'}}</p></div><div><button @click="flash('Look added to bag')">Add look</button><button @click="flash('Share link copied')">Share</button><button @click="looks=looks.filter(l=>l.id!==x.id)">Delete</button></div></article></template>
<template v-else-if="activeTab==='recent'"><div class="section-title split"><div><p class="eyebrow dark">Your browsing</p><h2>Recently viewed</h2></div><button class="btn btn-ghost" @click="recent=[]">Clear history</button></div><div class="wishlist-grid"><article v-for="x in recent" :key="x.name" class="dashboard-card saved-product"><div class="product-placeholder tall">MK</div><small>{{x.date}} · {{x.stock}}</small><h3>{{x.name}}</h3><p>US${{x.price}} <del v-if="x.oldPrice">US${{x.oldPrice}}</del> · {{x.sizes}}</p><button class="btn btn-primary" @click="flash('Added to bag')">Add to bag</button></article></div></template>
<template v-else-if="activeTab==='style'"><PageTitle eyebrow="A better fit" title="My sizes & style"/><form class="dashboard-card settings-form" @submit.prevent="saveStyle"><div class="form-grid-3"><label>Clothing size<input v-model="styleProfile.clothingSize"></label><label>Shoe size<input v-model="styleProfile.shoeSize"></label><label>Preferred fit<input v-model="styleProfile.fit"></label><label>Favourite colours<input v-model="styleProfile.colours"></label><label>Favourite styles<input v-model="styleProfile.styles"></label><label>Price range<input v-model="styleProfile.priceRange"></label><label>Favourite brands<input v-model="styleProfile.brands"></label><label>Shopping occasions<input v-model="styleProfile.occasions"></label><label>Fragrance family<input v-model="styleProfile.fragrance"></label></div><button class="btn btn-primary">Save style profile</button></form></template>
<template v-else-if="activeTab==='loyalty'"><PageTitle eyebrow="Maps Kayz rewards" title="Loyalty & rewards"/><div class="empty-state"><h3>No loyalty activity yet</h3><p>Points and rewards earned from real purchases and referrals will appear here.</p></div></template>
<template v-else-if="activeTab==='coupons'"><PageTitle eyebrow="Your offers" title="Coupons & promotions"/><div class="empty-state"><h3>No coupons available</h3><p>Coupons assigned to this account will appear here.</p></div></template>
<template v-else-if="activeTab==='credit'"><PageTitle eyebrow="Balances" title="Gift cards & store credit"/><div class="empty-state"><h3>No balance or activity</h3><p>Real gift-card and store-credit transactions will appear here.</p></div></template>
<template v-else-if="activeTab==='addresses'"><PageTitle eyebrow="Delivery destinations" title="Address book"/><p class="safe-note">Free delivery for Bulawayo residents. Addresses outside Bulawayo have a US$8 courier fee.</p><article v-for="a in addresses" :key="a.id" class="dashboard-card address-row"><span>{{a.label}}</span><div><strong>{{a.recipient}}</strong><p>{{a.phone}}<br>{{a.address}}<br><small>{{a.instructions}} · {{a.deliveryFee?'Delivery US$'+a.deliveryFee:'Free delivery'}}</small></p></div><div><em v-if="a.default">Default</em><button @click="removeRecord('addresses',a,addresses)">Delete</button></div></article><form class="dashboard-card settings-form" @submit.prevent="addAddress"><h3>Add an address</h3><div class="form-grid-3"><label>Label<select v-model="address.label"><option>Home</option><option>Work</option><option>Other</option></select></label><label>Recipient<input v-model="address.recipient" required></label><label>Phone<input v-model="address.phone" required></label><label>Province<input v-model="address.province" required></label><label>City<input v-model="address.city" required @blur="checkDelivery"></label><label>Suburb<input v-model="address.suburb"></label><label>Street<input v-model="address.street" required></label><label>House number<input v-model="address.house"></label></div><p v-if="deliveryQuote" class="alert alert-info">{{deliveryQuote.message}} · {{deliveryQuote.fee?'US$'+deliveryQuote.fee:'Free'}}</p><label>Delivery instructions<textarea v-model="address.instructions"></textarea></label><button class="btn btn-primary">Save address</button></form></template>
<template v-else-if="activeTab==='notifications'"><div class="section-title"><p class="eyebrow dark">Stay informed</p><h2>Notifications</h2></div><article v-for="n in notices" :key="n.id" class="notification-item" :class="{unread:!n.read}" @click="markNotice(n)"><i></i><div><strong>{{n.title}}</strong><p>{{n.body}}</p><small>{{n.type}} · {{n.time||'Just now'}}</small></div><button @click.stop="removeRecord('notifications',n,notices)">×</button></article><section class="dashboard-card preference-list"><h3>Notification preferences</h3><label v-for="(_,k) in prefs" :key="k"><span>{{k}}</span><input v-model="prefs[k]" type="checkbox" role="switch"></label><button class="btn btn-primary" @click="savePreferences">Save notification choices</button><small>Essential security and transaction messages always remain enabled.</small></section></template>
<template v-else-if="activeTab==='support'"><PageTitle eyebrow="We’re here to help" title="Support centre"/><div class="dashboard-two-col"><form class="dashboard-card settings-form" @submit.prevent="submitSupport"><h3>Open a ticket</h3><label>Category<select v-model="ticket.category"><option v-for="c in ['Order problem','Payment problem','Delivery problem','Product enquiry','Return or exchange','Account problem','Loyalty points','Complaint','Other']" :key="c">{{c}}</option></select></label><label>Related order<input v-model="ticket.order"></label><label>Subject<input v-model="ticket.subject" required></label><label>Message<textarea v-model="ticket.message" required></textarea></label><button class="btn btn-primary">Submit ticket</button></form><article class="dashboard-card support-panel"><h3>Talk to us</h3><p>Monday–Saturday, 08:00–18:00.<br>WhatsApp: 078 165 7310</p><a class="btn btn-primary" href="https://wa.me/263781657310" target="_blank">WhatsApp support</a><h3>Tickets are saved to your account</h3><p>Replies and status updates will appear in Notifications.</p></article></div></template>
<template v-else-if="activeTab==='reviews'"><PageTitle eyebrow="Share your experience" title="Reviews & questions"/><article class="dashboard-card review-card"><div class="product-placeholder">MK</div><div><span class="status-pill">Verified purchase</span><h3>{{review.product}}</h3><div class="stars"><button v-for="x in 5" :key="x" :class="{selected:x<=review.rating}" @click="review.rating=x">☆</button></div><input v-model="review.fit" placeholder="Size and fit"><textarea v-model="review.comment" placeholder="Write your review"></textarea><button class="btn btn-primary" @click="submitReview">Submit review</button></div></article><article class="dashboard-card settings-form"><h3>Ask a product question</h3><input v-model="question.product" placeholder="Product"><textarea v-model="question.message" placeholder="What would you like to know?"></textarea><button class="btn btn-primary" @click="submitQuestion">Send question</button></article></template>
<template v-else-if="activeTab==='referrals'"><PageTitle eyebrow="Share the style" title="Refer a friend"/><section class="referral-card"><small>Your referral code is your saved phone number</small><strong>{{profile.phone||'Add your number'}}</strong><p>Share your personal registration link on WhatsApp and earn 250 points after a successful referral.</p><button @click="shareReferral">Share referral on WhatsApp</button></section></template>
<template v-else-if="activeTab==='profile'"><PageTitle eyebrow="Personal details" title="Profile"/><form class="dashboard-card settings-form" @submit.prevent="saveProfile(false)"><div class="avatar-edit"><img v-if="profilePhoto" :src="profilePhoto" alt="Profile photo"><span v-else>{{initials}}</span><label class="btn btn-ghost">Upload photo<input type="file" accept="image/*" hidden @change="uploadPhoto"></label></div><div class="form-grid-2"><label>Full name<input v-model="profile.name"></label><label>Email<input v-model="profile.email" type="email" disabled><small>Email changes require verification.</small></label><label>Phone<input v-model="profile.phone"></label><label>WhatsApp<input v-model="profile.whatsapp"></label><label>Date of birth<input v-model="profile.birthday" type="date"></label><label>Language<select v-model="profile.language"><option>English</option><option>Shona</option><option>Ndebele</option></select></label><label>Currency display<select v-model="profile.currency"><option>USD</option><option>ZAR</option></select></label></div><button class="btn btn-primary">Save now</button></form></template>
<template v-else-if="activeTab==='security'"><PageTitle eyebrow="Account protection" title="Privacy & security"/><section class="dashboard-card preference-list"><label><span><strong>Two-factor authentication</strong><small>Verification when you sign in.</small></span><input v-model="privacy.twoFactor" type="checkbox"></label><label><span><strong>Marketing consent</strong><small>Offers and product news.</small></span><input v-model="privacy.marketing" type="checkbox"></label><label><span><strong>Analytics cookies</strong><small>Improve your experience.</small></span><input v-model="privacy.cookies" type="checkbox"></label></section><section class="dashboard-card"><h3>Active devices</h3><div class="device-row"><div><strong>Chrome on Windows</strong><p>Harare · Active now</p></div><span class="status-pill">This device</span></div><div class="device-row"><div><strong>Safari on iPhone</strong><p>Harare · 4 Sep 2026</p></div><button @click="flash('Session ended')">End session</button></div></section><section class="dashboard-card danger-zone"><h3>Sensitive actions</h3><button v-for="x in ['Change password','Download personal data','Log out all devices','Request account deletion']" :key="x" @click="flash(x+' requires verification')">{{x}}</button></section></template>
</main></div></div></template>

<script>
const PageTitle={props:['eyebrow','title'],template:`<div class="section-title"><p class="eyebrow dark">{{eyebrow}}</p><h2>{{title}}</h2><p v-if="['Wishlist','Saved looks','Recently viewed'].includes(title)">No saved activity yet. Use the shop to add items here.</p></div>`}
const SettingsForm={emits:['saved'],template:`<form class="dashboard-card settings-form" @submit.prevent="$emit('saved')"><div class="form-grid-3"><label>Clothing size<select><option>Medium</option><option>Small</option><option>Large</option></select></label><label>Shoe size<input value="39"></label><label>Preferred fit<select><option>Relaxed</option><option>Tailored</option></select></label><label>Favourite colours<input value="Black, ivory, rust"></label><label>Favourite styles<input value="Minimal, tailored"></label><label>Price range<select><option>US$40–US$150</option></select></label><label>Favourite brands<input placeholder="Add brands"></label><label>Shopping occasions<input value="Work, events"></label><label>Fragrance family<select><option>Woody</option><option>Floral</option></select></label></div><button class="btn btn-primary">Save profile</button></form>`}
export default {components:{PageTitle,SettingsForm}}
</script>
