// Mirrors backend/src/database/entities/platform-record.entity.ts PLATFORM_RESOURCES
// exactly. These are the resource names accepted by the generic /platform/:resource
// CRUD API (backend/src/platform). Kept as a flat list so the admin "Platform Records"
// page can offer every one of them from a single dropdown instead of 150 bespoke pages.
export const PLATFORM_RESOURCES = [
  'account-deletion-requests', 'analytics-events', 'announcement-bars', 'backup-records',
  'branch-expenses', 'branch-hours', 'bundle-items', 'campaign-attributions', 'cart-items',
  'collection-points', 'collections', 'colours', 'comparison-lists', 'content-revisions',
  'customer-communications', 'customer-data-requests', 'customer-notes', 'customer-segments',
  'customer-sessions', 'customer-tags', 'delivery-attempts', 'delivery-proofs', 'device-sessions',
  'dispatch-documents', 'faqs', 'fit-feedback', 'gift-card-transactions', 'incident-records',
  'inventory-batches', 'inventory-counts', 'inventory-discrepancies', 'inventory-forecasts',
  'inventory-valuations', 'invoices', 'login-activity', 'loyalty-levels', 'loyalty-rewards',
  'notification-preferences', 'order-fulfilments', 'order-history', 'order-notes', 'packing-slips',
  'picking-lists', 'pos-offline-transactions', 'pos-receipts', 'product-approval-requests',
  'product-import-jobs', 'product-reports', 'product-revisions', 'purchase-order-items', 'receipts',
  'return-inspections', 'return-items', 'review-replies', 'saved-carts', 'saved-items',
  'search-history', 'search-synonyms', 'security-alerts', 'seo-records', 'sizes', 'staff-activity',
  'stocktake-items', 'stock-transfer-items', 'store-credit-transactions', 'styling-requests',
  'supplier-documents', 'supplier-price-lists', 'supplier-product-mappings', 'supplier-ratings',
  'support-attachments', 'support-saved-responses', 'tags', 'trending-searches',
  'unsubscribe-records', 'verification-requests', 'warehouse-locations', 'wishlist-items',
  'checkout-sessions', 'data-retention-policies', 'delivery-performance', 'file-uploads',
  'idempotency-keys', 'malware-scan-results', 'performance-metrics', 'product-recommendations',
  'rate-limit-events', 'report-exports', 'scheduled-jobs', 'search-indexes',
  'size-recommendations', 'system-health-events', 'translations', 'uptime-alerts',
  'user-profiles', 'webhook-events', 'addresses', 'branches', 'warehouses', 'suppliers',
  'supplier-catalogues', 'purchase-requisitions', 'purchase-orders', 'goods-received-notes',
  'supplier-invoices', 'purchase-returns', 'brands', 'product-variations', 'product-media',
  'size-guides', 'pricing-rules', 'promotions', 'coupons', 'loyalty-accounts',
  'loyalty-transactions', 'gift-cards', 'store-credit', 'delivery-zones', 'couriers',
  'exchanges', 'pos-sales', 'pos-shifts', 'cash-movements', 'stocktakes', 'stock-transfers',
  'support-tickets', 'support-messages', 'reviews', 'product-questions', 'wishlists',
  'saved-searches', 'restock-alerts', 'price-drop-alerts', 'carts', 'abandoned-carts',
  'outfit-bundles', 'saved-outfits', 'styling-profiles', 'measurement-profiles',
  'content-pages', 'homepage-sections', 'navigation-menus', 'banners', 'lookbooks',
  'blog-posts', 'redirects', 'marketing-campaigns', 'marketing-templates', 'consent-records',
  'affiliate-codes', 'customer-content', 'notifications', 'notification-templates',
  'audit-logs', 'staff', 'roles', 'permissions', 'approval-requests', 'reports',
  'scheduled-reports', 'system-settings',
]
